name: Build and Deploy
on:
    push:
        tags:
            -v*
jobs:
    build:
        name: Build app
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: '10.x'
            - run: yarn install
            - run: yarn build
            - uses: actions/upload-actifact@v1
              with:
                name: build
                path: build/
        
            
#test
